[pyprland]
plugins = ["scratchpads", "expose", "magnify"]

[scratchpads.volume]
command = "pavucontrol"
unfocus = "hide"
position = "1% 8%"
lazy = true
force_monitor = "DP-1"

[scratchpads.terminal]
command = "kitty --class scratchpad-large"
excludes = ["dots"]
lazy = true

[scratchpads.yazi]
command = "kitty --class scratchpad-large yazi"
lazy = true

[scratchpads.gpt]
command = "kitty --class scratchpad-large tgpt -m"
lazy = true

[scratchpads.dots]
command = "kitty --class scratchpad-large yadm enter lazygit"
excludes = ["terminal"]
lazy = true

[scratchpads.btop]
command = "kitty --class scratchpad-large btop"
lazy = true

[scratchpads.bluetooth]
command = "blueman-manager"
animation = "fromRight"
unfocus = "hide"
margin = 20
lazy = true

[wallpapers]
path = "/home/matt/.config/hypr/themes/luna/walls/"
interval = 60                                                                                                              # change every hour
command = "swww img --transition-bezier 0.5,1.19,.8,.4 --transition-type wipe --transition-duration 2 --transition-fps 75"
clear_command = "swww clear"
extensions = ["jpg", "png", "gif", "jpeg"]
