"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]

prepend_keymap = [
  { on = [
    "<C-s>",
  ], run = '''shell "$SHELL" --block --confirm''', desc = "Open shell here" },
  { on = [
    "c",
    "a",
  ], run = "plugin compress", desc = "Archive selected files" },
  { on = "<C-u>", run = "seek -5", desc = "Seek up 5 units in the preview" },
  { on = "<C-d>", run = "seek 5", desc = "Seek down 5 units in the preview" },
  { on = "K", run = "arrow -50%", desc = "Move cursor up half page" },
  { on = "J", run = "arrow 50%", desc = "Move cursor down half page" },
  { on = "<A-k>", run = "arrow -5", desc = "Move cursor up half page" },
  { on = "<A-j>", run = "arrow 5", desc = "Move cursor down half page" },
]

append_keymap = [
  { on = [
    "e",
  ], run = "open", desc = "Open the selected files" },
  { on = [
    "E",
  ], run = "open --interactive", desc = "Open the selected files interactively" },
  { on = [
    "g",
    "n",
  ], run = "cd ~/.config/nvim/", desc = "Go to the nvim directory" },
  { on = [
    "g",
    "v",
  ], run = "cd ~/Videos/", desc = "Go to the videos directory" },
  { on = [
    "g",
    "i",
  ], run = "cd ~/Pictures/", desc = "Go to the images directory" },
  { on = [
    "g",
    "s",
  ], run = "cd ~/Pictures/Screenshots/", desc = "Go to the screenshots directory" },
  { on = [
    "g",
    "D",
  ], run = "cd ~/Documents/", desc = "Go to the docs directory" },
  { on = [
    "g",
    "o",
  ], run = "cd ~/Documents/Obsidian/obsidianVault/", desc = "Go to the obsidian directory" },
  { on = [
    "g",
    "r",
  ], run = "cd ~/Repos/", desc = "Go to the repos directory" },
]

[input]

prepend_keymap = [{ on = ["<Esc>"], run = "close", desc = "Cancel input" }]
